annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.31.4
description: A Library Helm Chart for grouping common logic between iamguarded charts.
  This chart is not deployable by itself.
home: https://chainguard.dev
keywords:
- common
- helper
- template
- function
- iamguarded
name: common
type: library
version: 2.31.4
